apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hugo-app-dep
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hugo-app
    spec:
      containers:
        - name: hugo-app
          image: drlee001/hugo-app:1.0
          ports:
            - containerPort: 80
